# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: When Code Goes Wrong
email: samjacobclift@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have been doing a lot of interesting things recently and I would like to share them with anyone who is interested!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://royka.github.io" # the base hostname & protocol for your site
twitter_username: samclift
github_username:  royka

# Build settings
markdown: kramdown
